n_simulations: 5
n_rounds: 1000
n_states: 3
n_messages: 2
prior_name: uniform
utility_name: equality

sender_name: threshold
receiver_name: exp3

# For the threshold sender
threshold: 0.1

# For the UCB receiver
delta_exponent: 1

# For the Exp3 receiver
eta: 1.1